--create table candidates (
--    candidate_id integer generated by default as identity (start with 1),
--    age integer check (age>=18 AND age<=70),
--    name varchar(30) not null,
--    primary key (candidate_id)
--);

--create table interviews (
--    interview_id integer generated by default as identity (start with 1),
--    interview_date timestamp,
--    candidate_id integer,
--    primary key (interview_id)
--);

--alter table interviews 
--    add constraint interviews_fk1 
--    foreign key (candidate_id) 
--    references candidates;