-- Difficulties
create table difficulties (
    val         integer     not null,
    name        varchar(32) not null,
    description varchar(512),
    
    primary key (val)
);

-- Tags
create table tags (
    name        varchar(64) not null,
    description varchar(512),
    
    primary key (name)
);

-- Questions
create table questions (
    question_id     integer      generated by default as identity (start with 1),
    question        varchar(128) not null,
    expected_answer varchar(512),
    difficulty      integer,
    
    primary key (question_id)
);

alter table questions 
    add constraint fk_questions01 
    foreign key (difficulty) 
    references difficulties;

-- Question / Tags
create table question_tags (
    question_id integer     not null,
    tag_name    varchar(64) not null,
    
    primary key (question_id, tag_name)
);

alter table question_tags 
    add constraint fk_question_tags01 
    foreign key (question_id) 
    references questions;

alter table question_tags 
    add constraint fk_question_tags02 
    foreign key (tag_name) 
    references tags;

-- Candidates
create table candidates (
    candidate_id integer     generated by default as identity (start with 1),
    name         varchar(30) not null,
    age          integer     check (age >= 18 and age <= 70),
    
    primary key (candidate_id)
);

-- Interviews
create table interviews (
    interview_id   integer generated by default as identity (start with 1),
    candidate_id   integer,
    interview_date timestamp,
    
    primary key (interview_id)
);

alter table interviews 
    add constraint fk_interview01 
    foreign key (candidate_id) 
    references candidates;

-- Interview / Asked Questions
create table interview_asked_questions (
    interview_id integer,
    question_id  integer,    
    grade        varchar(14) not null,
    comments     varchar(512),
    
    primary key (interview_id, question_id)
);

alter table interview_asked_questions 
    add constraint fk_interview_asked_questions01
    foreign key (question_id) 
    references questions;

alter table interview_asked_questions 
    add constraint fk_interview_asked_questions02 
    foreign key (interview_id) 
    references interviews;

